const firstName = [
    {Value : "Abeille", Gender : "F"},
    {Value : "Artichaut", Gender : "M"},
    {Value : "Asperge", Gender : "F"},
    {Value : "Bécasse", Gender : "F"},
    {Value : "Belette", Gender : "F"},
    {Value : "Bélier", Gender : "M"},
    {Value : "Blaireau", Gender : "M"},
    {Value : "Brebis", Gender : "F"},
    {Value : "Brocoli", Gender : "M"},
    {Value : "Cacahuète", Gender : "F"},
    {Value : "Cachalot", Gender : "M"},
    {Value : "Cafard", Gender : "M"},
    {Value : "Caïman", Gender : "M"},
    {Value : "Campagnol", Gender : "M"},
    {Value : "Carotte", Gender : "F"},
    {Value : "Céleri", Gender : "M"},
    {Value : "Chimpanzé", Gender : "M"},
    {Value : "Cochon d'inde", Gender : "F"},
    {Value : "Coléoptère", Gender : "M"},
    {Value : "Courgette", Gender : "F"},
    {Value : "Crapaud", Gender : "M"},
    {Value : "Diplodocus", Gender : "M"},
    {Value : "Echalotte", Gender : "F"},
    {Value : "Endive", Gender : "F"},
    {Value : "Faisan", Gender : "M"},
    {Value : "Faucon", Gender : "M"},
    {Value : "Fenouil", Gender : "M"},
    {Value : "Flageolet", Gender : "M"},
    {Value : "Gerbille", Gender : "F"},
    {Value : "Gingembre", Gender : "M"},
    {Value : "Grive", Gender : "F"},
    {Value : "Grenouille", Gender : "F"},
    {Value : "Haricot noir", Gender : "M"},
    {Value : "Héron", Gender : "M"},
    {Value : "Hirondelle", Gender : "F"},
    {Value : "Homard", Gender : "M"},
    {Value : "Iguane", Gender : "M"},
    {Value : "Lémurien", Gender : "M"},
    {Value : "Lézard", Gender : "M"},
    {Value : "Manchot", Gender : "M"},
    {Value : "Moineau", Gender : "M"},
    {Value : "Moufette", Gender : "F"},
    {Value : "Mulot", Gender : "M"},
    {Value : "Musaraigne", Gender : "F"},
    {Value : "Navet", Gender : "M"},
    {Value : "Ouistiti", Gender : "M"}, 
    {Value : "Pangolin", Gender : "M"},
    {Value : "Paresseux", Gender : "M"},
    {Value : "Patate douce", Gender : "F"},
    {Value : "Phacochère", Gender : "M"},
    {Value : "Phasme", Gender : "M"},
    {Value : "Piment", Gender : "M"},
    {Value : "Pingouin", Gender : "M"},
    {Value : "Poule", Gender : "F"},
    {Value : "Putois", Gender : "M"},
    {Value : "Radis", Gender : "M"},
    {Value : "Raton", Gender : "M"},
    {Value : "Raptor", Gender : "M"},
    {Value : "Rhinocéros", Gender : "M"},
    {Value : "Salamandre", Gender : "F"},
    {Value : "Seiche", Gender : "F"},
    {Value : "Taureau", Gender : "M"},
    {Value : "Termite", Gender : "F"},
    {Value : "Topinambour", Gender : "M"},
    {Value : "Vautour", Gender : "M"},
    {Value : "Vache", Gender : "F"},
    {Value : "Varan", Gender : "M"},
    {Value : "Zébulon", Gender : "M"}
];

const lastName = [
    {N : "acariâtre"},
    {N : "acerbe"},
    {F : "agitée", M :"agité"},
    {N : "aigre"},
    {F : "alarmée", M :"alarmé"},
    {F : "anéantie", M :"anéanti"},
    {F : "appeurée", M :"appeuré"},
    {F : "attentive", M :"attentif"},
    {N : "austère"},
    {F : "bourrée", M :"bourré"},
    {F : "bourrue", M :"bourru"},
    {F : "castrante", M :"castrant"},
    {N : "coriace"},
    {F : "crispée", M :"crispé"},
    {N : "cynique"},
    {F : "désabusée", M :"désabusé"},
    {F : "désappointée", M :"désappointé"},
    {F : "disciplinée", M :"discipliné"},
    {F : "dissidente", M :"dissident"},
    {F : "désappointée", M :"désappointé"},
    {F : "dribbleuse", M :"dribbleur"},
    {F : "échauffée", M :"échauffé"},
    {F : "éclairée", M :"éclairé"},
    {F : "émotive", M :"émotif"},
    {F : "énervée", M :"énervé"},
    {F : "entêtée", M :"entêté"},
    {F : "excitée", M :"excité"},
    {N : "fébrile"},
    {F : "grailleuse", M :"grailleur"},
    {F : "grincheuse", M :"grincheux"},
    {N : "imblairable"},
    {N : "innommable"},
    {F : "inquiète", M :"inquiet"},
    {F : "insatisfaite", M :"insatisfait"},
    {N : "instable"},
    {N : "intraitable"},
    {F : "irradiée", M :"irradié"},
    {F : "irritée", M :"irrité"},
    {F : "folle de rage", M :"fou de rage"},
    {F : "frustrée", M : "frustré"},
    {F : "hors d'elle", M : "hors de lui"},
    {N : "hystérique"},
    {N : "maussade"},
    {F : "mécontente", M : "mécontent"},
    {F : "minutieuse", M :"minutieux"},
    {F : "motivée", M :"motivé"},
    {F : "musculeuse", M :"musculeux"},
    {F : "nerveuse", M :"nerveux"},
    {F : "nervurée", M :"nervuré"},
    {N : "névrotique"},
    {F : "obtuse", M : "obtus"},
    {F : "offensive", M : "offensif"},
    {F : "outrée", M :"outré"},
    {N : "perplexe"},
    {F : "remontée", M :"remonté"},
    {F : "remuante", M :"remuant"},
    {F : "réticente", M :"réticent"},
    {N : "revêche"},
    {F : "ronchonne", M :"ronchon"},
    {F : "rugeuse", M :"rugeux"},
    {F : "sèche", M :"sec"},
    {F : "soucieuse", M :"soucieux"},
    {F : "scrupuleuse", M :"scrupuleux"},
    {F : "taquine", M :"taquin"},
    {F : "turbulente", M :"turbulent"},
    {F : "vexée", M :"vexé"},
    {F : "visqueuse", M :"visqueux"},
];